### ISSUE TITLE
Crash on 'Opening archive songs.psarc...' (Linux/Wine)

### ISSUE THREAD

**Issue by LegitGreenBoi** [spontiroli/rocksmith2tab#1]
Tried running this on Linux using Bottles with Wine (soda-8.0-2).

I get a crash when creating tabs. Here's the log output:

```
[1/2176] Opening archive songs.psarc ...

Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'RocksmithToolkitLib, Version=2.6.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Bad format.
   at RocksmithToTab.Program.ExportPsarc(String psarcFile, CmdOptions options)
   at RocksmithToTab.Program.Main(String[] args)
```

The original rocksmith2tab works as expected with the same bottle. (Other than the known issue with rs1compatibilitydlc_p.psarc)

**Comment by spontiroli** [comment]
Thank you for reporting it. I'll take a look; most likely, I'm missing a DLL in the package.

**Comment by spontiroli** [comment]
The issue is due to an architecture mismatch between the [RocksmithToolkitLib.dll](https://github.com/rscustom/rocksmith-custom-song-toolkit) and the rocksmith2tab architecture. I can quickly build everything using x86 (and upload a new release), and then I can take a bit more time and get everything working in x64.

**Comment by LegitGreenBoi** [comment]
> The issue is due to an architecture mismatch between the [RocksmithToolkitLib.dll](https://github.com/rscustom/rocksmith-custom-song-toolkit) and the rocksmith2tab architecture. I can quickly build everything using x86 (and upload a new release), and then I can take a bit more time and get everything working in x64.

Nice, let me know when the new build is up and I'll try it out

**Comment by spontiroli** [comment]
I uploaded a new [release ](https://github.com/spontiroli/rocksmith2tab/releases/tag/rocksmith2tab-alpha-0.2)(x86); whenever you have a chance, could you try it out?

**Comment by LegitGreenBoi** [comment]
> I uploaded a new [release ](https://github.com/spontiroli/rocksmith2tab/releases/tag/rocksmith2tab-alpha-0.2)(x86); whenever you have a chance, could you try it out?

Just tried the new build, works great. Thanks for getting it out quickly!
